apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: unknown-app.dev
      http:
        paths:
          - path: /blogs/all/?(.*)
            backend:
              serviceName: blog-backend-srv
              servicePort: 8080
          - path: /?(.*)
            backend:
              serviceName: blog-client-srv
              servicePort: 3000